# Generated by Django 3.1.4 on 2020-12-15 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(10)])),
                ('evolution_level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(10)])),
                ('image', models.CharField(blank=True, max_length=100)),
                ('evolution_to', models.CharField(blank=True, max_length=100)),
                ('abilities', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
