# Generated by Django 3.1.4 on 2020-12-16 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='Uid',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
